/*
 * Copyright (c) 2019-2026 Airbus Commercial Aircraft
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * As an additional exemption you are allowed to compile & link against the
 * OpenSSL libraries as published by the OpenSSL project. See the file
 * COPYING for details.
 *
 */


/* ---------------------------------------------------------------------
 * Crash Recovery - logger main
 *
 * Reads in existing unencrypted (plain) log file and converts it according BN19
 *
 * [BN19] Erik-Oliver Blass and Guevara Noubir.
 * Forward Integrity and Crash Recovery for Secure Logs. Cryptology ePrint Archive, Paper 2019/506. 2019.
 * url: https://eprint.iacr.org/2019/506.
 *
 * This implementation was ported from Florian Hördt's master thesis example C++ code into C.
 * https://github.com/Genfood/secure-logging-cr
 *
 * NOTE: The count of lines in the file given must be at least 5 (THE_K)
 * The input file is line-oriented. The line length must not exceed 2048 bytes.
 * UTF-8 is supported. 2048 octes does not mean 2048 characters or symbols.
 * Each UTF-8 symbol might  be 4 bytes long.
 *
 * Currently the key (master key) is generated by this logger, when
 * there is none. Existing session key is deleted!
 * The master key then is used later by the verifier.
 *
 * Arguments
 * --key, -k:     Full file name (path) of initial key
 * --in, -i:      Full file name (path) of the line-oriented input plain text file
 * --out, -o:     Full file name (path) of the encrypted output file
 * --maxlogs, -m: Number of log lines the original plain log file provides
 *
 * Returns 0 on SUCCESS and non-zero on FAILURE (main logic)
 */


#include <stdio.h>
#include <locale.h>
#include <sys/types.h>
#include <string.h>
#include <stdlib.h>
#include <glib.h>
#include <math.h> //-- ceil 
#include <openssl/rand.h>
#include <openssl/evp.h>
#include <openssl/sha.h>

#include "utils_slog.h"
#include "cr_crypto.h"
#include "cr_pi_shared.h"
#include "cr_pi_logger_context.h"
#include "cr_pi_logger.h"



#define MAX_LINE_LENGTH MESSAGE_LEN_SLOGCR /* octet length of the define max log length (this is NOT the number of characters or symbols) */

GPtrArray *cr_pi_logger_main_read_logs_glib(const gchar *path, gint max_log_count, GError **error);


static void unref_gstring_wrapper(void *data)
{
  // The FALSE here ensures only the GString structure is freed
  // if you want to keep the data, but usually in a free_func
  // you want TRUE to free the character data as well.
  if (data)
    g_string_free((GString *)data, TRUE);
}


//----------------------------------------------------------------------
// main
//
// returns 0 only in case of success (main logic).

int main(int argc, char *argv[])
{
  setlocale(LC_ALL, "");
  gboolean is_arg_key = FALSE;
  gboolean is_arg_in = FALSE;
  gboolean is_arg_out = FALSE;
  gboolean is_arg_maxlogs = FALSE;

  if (1 > argc)
    {
      g_printerr("ERROR: cr_logger: Wrong count of arguments!\n");
      return 1; //-- ERROR
    }

  GOptionEntry entries[] =
  {
    { "key", 'k', 0, G_OPTION_ARG_NONE, &is_arg_key, "Full file name (path) of the master key", NULL },
    { "in", 'i', 0, G_OPTION_ARG_NONE, &is_arg_in, "Full file name (path) of the line-oriented input plain text file", NULL }, //-- first param of readLogs
    { "out", 'o', 0, G_OPTION_ARG_NONE, &is_arg_out, "Full file name (path) of the encrypted output file", NULL }, //-- 4th param of CreatePIContext, used as filename without extension
    { "maxlogs", 'm', 0, G_OPTION_ARG_NONE, &is_arg_maxlogs, "Number of log lines the original plain log file provides", NULL }, //-- maxlines to be read
    { 0 }
  };

  GError *error = NULL;
  GOptionContext *context;

  context = g_option_context_new ("- logger (Crash Recovery)");
  g_option_context_add_main_entries(context, entries, NULL);
  if (!g_option_context_parse(context, &argc, &argv, &error))
    {
      // If parsing failed, print the error and exit.
      g_printerr("ERROR: cr_logger: parsing options: %s\n", error->message);
      g_error_free(error);
      g_option_context_free(context);
      return 1; //-- ERROR
    }

  if ((5 != argc) && (FALSE == is_arg_key) && (FALSE == is_arg_in) && (FALSE == is_arg_out)
      && (FALSE == is_arg_maxlogs))
    {
      g_printerr("ERROR: cr_logger: Wrong count of arguments!\n");
      g_option_context_free(context);
      return 1; //-- ERROR
    }

  //-- check master key, --key, -k
  char szMasterKeyPath[PATH_MAX];
  strncpy(szMasterKeyPath, argv[1], PATH_MAX - 1);
  szMasterKeyPath[PATH_MAX - 1] = '\0';
  if ( ! g_file_test(szMasterKeyPath, G_FILE_TEST_IS_REGULAR))
    {
      g_printerr("ERROR: cr_logger: Invalid full file name of master key: %s\n", szMasterKeyPath);
      g_option_context_free(context);
      return 1; //-- ERROR
    }

  //-- check logs, --in, -i
  // InputFileName: plain test log file to read
  char szInputFileName[PATH_MAX];
  strncpy(szInputFileName, argv[2], PATH_MAX);
  szInputFileName[PATH_MAX - 1] = '\0';
  if ( ! g_file_test(szInputFileName, G_FILE_TEST_IS_REGULAR))
    {
      g_printerr("ERROR: cr_logger: Invalid full log file name %s\n", szInputFileName);
      g_option_context_free(context);
      return 1; //-- ERROR
    }

  //-- check output filename, --out, -o
  // OutputFileName: encrypted log file to write
  char szOutputFileName[PATH_MAX];
  char szOutputDir[PATH_MAX];
  strncpy(szOutputFileName, argv[3], PATH_MAX);
  szOutputFileName[PATH_MAX - 1] = '\0';
  gboolean is_valid_dir_from_file = get_path_from_file(szOutputFileName, szOutputDir, sizeof(szOutputDir));
  if (FALSE == is_valid_dir_from_file)
    {
      g_printerr("ERROR: cr_logger: Invalid file path (directory from file is invalid) %s\n", szOutputFileName);
      g_option_context_free(context);
      return 1; //-- ERROR   (alternative: mkdir -p ...)
    }
  char last = szOutputDir[strlen(szOutputDir)];
  if ( '/' != last )
    {
      strncat(szOutputDir, "/", PATH_MAX - 1);
    }

  //-- check maxlogs
  int maxlogs;
  gchar *endptr;
  long int litemp = strtol(argv[4], &endptr, 10);
  if (*endptr != '\0')
    {
      g_printerr("ERROR: cr_logger: Invalid maxlogs, expected a number: %s\n", argv[4]);
      g_option_context_free(context);
      return 1; //-- ERROR
    }
  if (litemp > INT_MAX)
    {
      g_printerr("ERROR: cr_logger: maxlogs expected to be less or equal INT_MAX: %s\n", argv[4]);
      g_option_context_free(context);
      return 1; //-- ERROR
    }
  maxlogs = (int) litemp;
  if (maxlogs <= THE_K) //-- endless loop protection when filling Random buffer
    {
      //-- anyhow, maxlogs should be at least 4096 to be reliable ensure Crash Recovery,
      //   see https://eprint.iacr.org/2019/506.pdf, p 22, fig 3
      g_printerr("ERROR: cr_logger: Out of range: maxlogs: %d\n", maxlogs);
      g_option_context_free(context);
      return 1; //-- ERROR
    }

  g_print("key (initial key): %s\n", argv[1]);
  g_print("in (plain log file): %s\n", argv[2]);
  g_print("out (enc log file): %s\n", argv[3]);
  g_print("maxlogs (count of log lines): %s\n", argv[4]);

  g_option_context_free(context);

  g_print("szMasterKeyPath: %s\n", szMasterKeyPath);
  g_print("szInputFileName: %s\n", szInputFileName);
  g_print("szOutputFileName: %s\n", szOutputFileName);
  g_print("szOutputDir: %s\n", szOutputDir); //-- derived from szOutputFileName. Will NOT be created. Must exist.
  g_print("maxlogs: %d\n", maxlogs);

  cr_pi_logger_context loggerCtx = {NULL, NULL, NULL, NULL, INT_MAX};

  loggerCtx.p_MasterKeyPath = szMasterKeyPath;
  loggerCtx.p_OutputDirectoryPath = szOutputDir;
  loggerCtx.p_InputPlainLogPath = szInputFileName;
  loggerCtx.p_OutputEncLogPath = szOutputFileName;
  loggerCtx.maxLogs = maxlogs;

  //-- READ plain log file ---

  // read the logs from the provided log file.
  // char **logs = cr_pi_logger_main_readLogs(loggerCtx.logPath, &logCount, loggerCtx.maxLogs);
  char szBuffer[256];
  memset(szBuffer, 0, sizeof(szBuffer));
  get_human_timestamp(szBuffer);
  g_print("%s\n", szBuffer);
  struct timespec start, end;
  start = get_ts_now();
  error = NULL;
  GPtrArray *gpa_logs = cr_pi_logger_main_read_logs_glib(loggerCtx.p_InputPlainLogPath, loggerCtx.maxLogs, &error);
  if (error)
    {
      g_printerr("ERROR: cr_logger: Failed to read log file: %s\n", error->message);
      g_error_free(error);
      return 1; //-- ERROR
    }
  if (NULL == gpa_logs)
    {
      g_printerr("ERROR: cr_logger: Failed to read log file! (NULL == gpa_logs)\n");
      return 1; //-- ERROR
    }
  //-- log file read. Lines as GString*'s in gap_logs.

  // Create a Logger Context struct, which contains all important information, like the maxmum number of log files.
  cr_PIContext *ctx = cr_CreatePIContext(gpa_logs->len, TRUE, loggerCtx.p_MasterKeyPath, loggerCtx.p_OutputDirectoryPath,
                                         loggerCtx.p_OutputEncLogPath);
  if (NULL == ctx)
    {
      return 1; //-- ERROR
    }
  // Call the init algorithm.
  // This will initialize the log file of the according size, and will write the pseudo random pad.
  if (FALSE == cr_Init(ctx) )
    {
      g_printerr("ERROR: cr_logger: cr_Init,  Initialization failed!\n");
      g_free(ctx->keyPath);
      g_free(ctx);
      g_ptr_array_free(gpa_logs, TRUE);
      return 1; //-- ERROR
    }

  gboolean is_add = FALSE;
  g_print("gpa_logs->len: %d\n\n", gpa_logs->len);
  for (guint i = 0; i < gpa_logs->len; ++i)
    {
      // Pass the modified string to AddLogEntry (add item).
      GString *line = (GString *) g_ptr_array_index(gpa_logs, i);
      if (line->len > MAX_LINE_LENGTH)
        {
          g_warning("Log string is too long. Will be shortened! i: %d, Length: %ld, maximal allowed octet length: %d\n", i,
                    line->len,
                    MAX_LINE_LENGTH);
          g_print("Before truncate: %s\n", line->str);
          truncate_utf8_gstring(line, MAX_LINE_LENGTH);
          g_print("After truncate: %s\n", line->str);
        }
      if ( (0 == (i & 511)) || (i == (gpa_logs->len - 1)))
        {
          g_print("\x1b[2K\r  process line %d of %d", i + 1, gpa_logs->len);
        }
      is_add = cr_AddLogEntry(ctx, (unsigned char *)(line->str), line->len); //-- line->len: count of octets
      if (FALSE == is_add)
        {
          g_print("ERROR: cr_logger:  cr_addLogEntry was not successful. break and quit.\n");
          g_printerr("cr_AddLogEntry fails\n");
          break; //-- ERROR, Note: Cancel on first error
        }

    } //-- for gpa_logs->len


  if (TRUE == is_add)
    {
      g_print("\n\ncr_logger: %d Logs have been written successfully\n", gpa_logs->len);
    }
  else
    {
      g_print("\n\ncr_logger: %d Logs have NOT been written successfully\n", gpa_logs->len);
    }


  //-- clean up
  if (ctx->logFile)
    {
      fclose(ctx->logFile);
      ctx->logFile = NULL;
    }
  if (ctx->keyFile)
    {
      fclose(ctx->keyFile);
      ctx->keyFile = NULL;
    }
  g_free(ctx->keyPath);
  ctx->keyPath = NULL;
  g_free(ctx);
  ctx = NULL;
  g_ptr_array_free(gpa_logs, TRUE);

  end = get_ts_now();
  (void) get_time_diff_in_milliseconds(start, end, "Crash Recovery Logger (read + encrypt)");
  g_print("\n");
  memset(szBuffer, 0, sizeof(szBuffer));
  get_human_timestamp(szBuffer);
  g_print("%s\n", szBuffer);

  //-- return value main logic
  if (FALSE == is_add)
    {
      return 1; //-- ERROR, main logic
    }
  return 0; //-- SUCCESS
}



/* ---------------------------------------------------------------------
 * cr_pi_logger_main_read_logs_glib
 *
 * in  path: full file name of log file to read
 * in  maxlogCount: Maximal count of lines that is read
 * in/out error
 *
 * The caller owns the returned GPtrArray.
 * When no longer needed, the caller has to clean up memory by
 * calling  g_ptr_array_free(gpa_logs, TRUE);
 * Note: The length of line is NOT limited. Caller can do this later
 * when needed. Also the new line is NOT stripped here.
 * When the input file is not utf-8 this function will normalize
 * it to utf-8 and replace invalid characters by hexdump.
 * In the returned GPtrArray of GString pointers, each string
 * is provided as provided by the input file.
 *
 * return GPtrArray of GStrings or NULL in case of error
 */
GPtrArray *cr_pi_logger_main_read_logs_glib(const gchar *path, gint max_log_count, GError **error)
{
  GIOChannel *channel = g_io_channel_new_file(path, "r", error);
  if (!channel)
    {
      g_print("ERROR: g_io_channel_new_file, file: %s\n", path);
      return NULL;
    }

  // --- Explicitly set encoding to NULL to read raw bytes ---
  // This prevents g_io_channel_read_line from trying to validate/convert
  // UTF-8 itself, which would cause a G_IO_STATUS_ERROR.
  GIOStatus encoding_status = g_io_channel_set_encoding(channel, NULL, error);
  if (encoding_status == G_IO_STATUS_ERROR)
    {
      g_print("ERROR: g_io_channel_set_encoding: %s\n", (*error)->message);
      g_io_channel_unref(channel);
      return NULL;
    }

  // We will read raw bytes, so no encoding is set.
  GPtrArray *gpa_logs = g_ptr_array_new_with_free_func(unref_gstring_wrapper);
  GIOStatus status = G_IO_STATUS_NORMAL;
  gchar *raw_line_buffer = NULL;
  gsize raw_line_len = 0;
  gboolean is_found_invalid = FALSE;

  // --- Main loop to read lines (raw) ---
  while (gpa_logs->len < (guint)max_log_count &&
         (status = g_io_channel_read_line(channel,
                                          &raw_line_buffer,
                                          &raw_line_len,
                                          NULL,
                                          error)) == G_IO_STATUS_NORMAL)
    {
      GString *sanitized_line = g_string_new("");
      const gchar *start = raw_line_buffer;
      const gchar *end_of_buffer = raw_line_buffer + raw_line_len;

      // --- Sanitization loop for the current line ---
      while (start < end_of_buffer)
        {
          const gchar *first_invalid = NULL;

          //-- Check the rest of the buffer for validity
          gboolean is_valid = g_utf8_validate(start,       // Start of chunk to check
                                              end_of_buffer - start, // Length of chunk
                                              &first_invalid); // Will point to bad byte

          if (is_valid)
            {
              //-- The rest of the buffer is valid UTF-8.
              //   Append it all and finish with this line.
              g_string_append_len(sanitized_line, start, end_of_buffer - start);
              break; // Exit the sanitization loop
            }
          else
            {
              //-- We found an invalid byte at 'first_invalid'.
              is_found_invalid = TRUE;
              //-- First, append the *valid* part before the bad byte.
              gssize valid_chunk_len = first_invalid - start;
              if (valid_chunk_len > 0)
                {
                  g_string_append_len(sanitized_line, start, valid_chunk_len);
                }

              //-- Now, append the bad byte as a hex string.
              //   We cast to guint8 to ensure it's treated as an unsigned 0-255 value.
              g_string_append_printf(sanitized_line, "%02X", (guint8)*first_invalid);

              //-- Move our 'start' pointer to *after* the bad byte
              //   to continue scanning.
              start = first_invalid + 1;
            }
        } // --- End of sanitization loop ---

      // Add the fully sanitized (and valid UTF-8) string to our array
      g_ptr_array_add(gpa_logs, sanitized_line); // g_ptr_array "steals" the string

      g_free(raw_line_buffer);
      raw_line_buffer = NULL; // Reset for the next g_io_channel_read_line
    }

  g_free(raw_line_buffer); // Clean up in case of loop exit/error

  if (TRUE == is_found_invalid)
    {
      g_print("WARNING: Input log file %s contains invalid bytes!\n", path);
    }

  if (G_IO_STATUS_ERROR == status)
    {
      //-- This only catches real I/O errors now
      g_print("G_IO_STATUS_ERROR\n");
      g_ptr_array_free(gpa_logs, TRUE); //-- Clean up
      g_io_channel_unref(channel);
      return NULL;
    }

  g_io_channel_unref(channel);
  return gpa_logs;
}

